// Generated by @fcalell/plugin-node — do not edit.
import board from "./board.ts";
import gate from "./gate.ts";
import mcp from "./mcp.ts";
import proposals from "./proposals.ts";
import runs from "./runs.ts";
import sessions from "./sessions.ts";

export const services = [board, gate, mcp, proposals, runs, sessions];
