// Generated by @fcalell/plugin-node — do not edit.
import board from "./board.ts";
import mcp from "./mcp.ts";
import proposals from "./proposals.ts";
import sessions from "./sessions.ts";

export const services = [board, mcp, proposals, sessions];
